'use client'

import { useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

import Header from "@/components/Header";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [toggleSideBar, setToggleSideBar] = useState(false)


  return (
    <html lang="en">
      <body className="bg-[#fafafa] flex relative h-screen overflow-y-hidden">
        <ThemeProvider>
          <SideNav toggleSideBar={toggleSideBar} setToggleSideBar={setToggleSideBar} />
          <div className={`${toggleSideBar ? "w-full " : "w-[95%] "} overflow-y-scroll main`}>
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
